### ISSUE TITLE
Click on empty taskbar space. Double click on empty space is no longer working in Windows 11 24H2 for Task Manager option

### ISSUE THREAD

**Issue by r-kh** [m1lhaus/windhawk-mods#16]
Click on empty taskbar space
taskbar-empty-space-clicks by m1lhaus

Hi.
Double click on empty space for Task Manager is no longer working in 24H2 (checked with clean new installation of Win11 24H2)
(but it still works for Show Desktop or Mute system volume options for example)

**Comment by Halbour** [comment]
It doesn't work for me too, but only from today.
