### ISSUE TITLE
Click on empty taskbar space; Missing supported actions 8-11

### ISSUE THREAD

**Issue by ZmaZes** [m1lhaus/windhawk-mods#17]
taskbar-empty-space-clicks v1.4 by @m1lhaus
Windows 11 23H2

Some trigger options are missing from the dropdown:
 - Combine Taskbar buttons
 - Open Start menu
 - Virtual key press
 - Start application

It seemed logical to me that these options would appear in the dropdown along with everything else. I couldn't find any other option to use them or any other instruction that would suggest there was a different way of selecting them. Apologies if I've misunderstood how these are supposed to be used or for what systems they are available for.

![image](https://github.com/user-attachments/assets/725cbdcd-e47a-43cf-86ab-6c05059798ac)
[debug_log.txt](https://github.com/user-attachments/files/17267444/debug_log.txt)

**Comment by m1lhaus** [comment]
Hello @ZmaZes,

it might sound dump, but can you please try to scroll over those dropdown items? It seems that scrollbar will always autohide after few seconds. See my screenshots where scrollbar is visible after opening, but it autohides after few seconds.

![image](https://github.com/user-attachments/assets/c6f8dd2d-48b3-4adc-8ddf-308fb9039c8c)

It is a built in feature of the GUI framework Windhawk is using.
