### ISSUE TITLE
multi-monitor: Open start menu on window taskbar is clicked

### ISSUE THREAD

**Issue by donsingh** [m1lhaus/windhawk-mods#19]
taskbar-empty-space-clicks @m1lhaus 

I'm using this mod to launch the start menu on doubleclick on taskbar. with 4 monitors, it would be nice to show the start menu on the window it is called.

**Comment by m1lhaus** [comment]
Hello @donsingh ,
unfortunatelly current implementation just sends Win keypress to the system. That opens the Start on the main screen even if your context/focus is on secondary screen. I will try to take a look if I can utilize UIAutomation API to find and click Start button API.
