### ISSUE TITLE
Combine Taskbar buttons freezes explorer.exe

### ISSUE THREAD

**Issue by Veri7ion** [m1lhaus/windhawk-mods#23]
I have "Double click / double tap on empty space" set to "Combine Taskbar buttons".

When I installed this mod last week it was working great.
Now when I double click on the taskbar my taskbar freezes and stays frozen until I click on it a few times and explorer.exe restarts and then the combine taskbar buttons function is applied.

I'm on Windows 11 24H2 Build 26100.2314 and I've tried closing all background programs.

![12-12-2024 HknogsLz00](https://github.com/user-attachments/assets/6c54d045-0ad1-4792-baf4-47b4c6fa1f69)

**Comment by m1lhaus** [comment]
Hello @Veri7ion , thx for the report. I can reproduce it on my side as well. However from a quick look I can't see what is wrong. The reg keys are still there and they are changing to same values. Maybe the notify-settings-changed message/mechanism is causing that. When I find some time I will have a look.
