### ISSUE TITLE
Grouped Windows get stuck on "Better Taskbar Autohide" mod

### ISSUE THREAD

**Issue by jvaldiviezo9** [m1lhaus/windhawk-mods#9]
Hi @Cirn09

While using the mod, I noticed that it used to have issues with grouped tabs. If I clicked on the grouped icon in the taskbar and then clicked on another window, the grouped thumbnails would get stuck and remain there until I made a selection.

I believe the default behavior should be to autohide them at the same time as the taskbar.
This happens on the latest version of Windows 11 (is the one I'm using)

Attached below is a picture of the issue.

![image](https://github.com/m1lhaus/windhawk-mods/assets/18518204/8ed22d12-dee0-41fc-baff-fac9b2b115de)

**Comment by m1lhaus** [comment]
Hi @jvaldiviezo9
I don't follow. Is this really about "Click on empty taskbar space" mod? Because the mod doesn't alter the Windows function in any hackish way with regards to taskbar autohide. It uses Windows API to just toggle the feature on/off. Therefore this missbehavior you're seeing is Windows explorer own thing 😣

**Comment by jvaldiviezo9** [comment]
Hi @m1lhaus, no, this is from "Better Taskbar Autohide" mod made by @Cirn09

**Comment by m1lhaus** [comment]
@jvaldiviezo9 then please take this issues to his repo then, I can't do much about it 😂
https://github.com/Cirn09/windhawk-mods

**Comment by jvaldiviezo9** [comment]
Ohhh! Sorry, seems like I've made a mistake. Thanks for taking the time to point me in the right direction!

**Comment by jvaldiviezo9** [comment]
@m1lhaus unfortunately seems like @Cirn09 doesn't have an option to put an "Issue" how could I made him know about this issue?

**Comment by m1lhaus** [comment]
Man, try harder 😀I see a contant info on his website https://blog.cirn09.xyz/ or just post to parent (top-level) repo to which the code can be merged the same you posted here. I am closing this, good luck 🤞
